### PR TITLE
MNEMONIC-633: Add Xiaojin Jiao to committer page of Apache Mnemonic-site

### PR DESCRIPTION
**Pull request by rhythmwind**
Signed-off-by: Zane <rhythmwind@hotmail.com>

### CODE REVIEW

**Review by yzz127 — CHANGES_REQUESTED** [review]
I think the committer's apache id is in lower case, could you please update? Thanks

**Comment by rhythmwind** [comment]
The id has been updated.

**Review by bigdata-memory — APPROVED** [review]
Good to me, thanks.

**Review by yzz127 — APPROVED** [review]
+1,  thanks!

**Pull request merged**
